# update-from: docker.io/alpine:latest
FROM docker.io/alpine@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
RUN apk add --no-cache dnsmasq libcap && \
    setcap cap_net_bind_service=+ep /usr/sbin/dnsmasq && \
    (adduser -D -H dnsmasq 2>/dev/null || true)
EXPOSE 53/udp 53/tcp
USER dnsmasq
CMD ["dnsmasq", "--no-daemon", "--no-resolv", \
     "--server", "1.1.1.1", "--server", "8.8.8.8"]
