//! The port vs. `tests/fixtures/output/`, byte for byte, in both modes.
//!
//! The fixtures are generated by `scripts/gen-output-fixture.py`, which
//! drives the real `agentcage.output` and `agentcage._timing` through
//! the real `click.echo` — once on a stream that claims to be a
//! terminal, once on one that does not. Every expectation in them was
//! computed, never typed.
//!
//! This is the other reader. It cannot import click, so reproducing
//! these bytes is the whole proof that the escapes, the padding and the
//! stream choice survived the port. `tests/test_output_fixture.py` is
//! the Python half; between them, an undeclared change to what a user
//! sees breaks one side or the other.
//!
//! The two modes are asserted separately and both matter. `color` is
//! what the styling functions return; `plain` is what
//! [`agentcage_cli::output::strip_ansi`] has to make of it, and it is
//! what lands in a pipe, a log or a CI transcript.

use agentcage_cli::{output, timing};
use serde_json::Value;

fn fixture(name: &str) -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/output")
        .join(format!("{name}.json"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

fn cases(doc: &Value) -> &Vec<Value> {
    doc["cases"].as_array().expect("cases")
}

fn args(case: &Value) -> Vec<&str> {
    case["args"]
        .as_array()
        .expect("args")
        .iter()
        .map(|a| a.as_str().expect("a string argument"))
        .collect()
}

fn text(case: &Value, mode: &str, stream: &str) -> String {
    case[mode][stream]
        .as_str()
        .expect("recorded stream")
        .to_owned()
}

/// What `click.echo` would write to `stream`, given a styled line.
///
/// One line, one trailing newline, and the escapes only if the
/// destination is a terminal. That is the entire contract of
/// [`output::echo`] and [`output::echo_err`], minus the part that asks
/// the operating system whether a file descriptor is a tty — which a
/// test cannot arrange for stdout without a pty and does not need to,
/// because the branch it selects is one line long.
fn echoed(line: &str, color: bool) -> String {
    if color {
        format!("{line}\n")
    } else {
        format!("{}\n", output::strip_ansi(line))
    }
}

// ── styled.json ──────────────────────────────────────────────

/// Every `kind: "value"` case: the styling functions' return values.
#[test]
fn styled_values_match_the_python() {
    let doc = fixture("styled");
    let mut checked = 0;
    for case in cases(&doc) {
        if case["kind"] != "value" {
            continue;
        }
        let id = case["id"].as_str().expect("id");
        let a = args(case);
        let produced = match case["fn"].as_str().expect("fn") {
            "dim" => output::dim(a[0]),
            "green" => output::green(a[0]),
            "red" => output::red(a[0]),
            "banner_text" => output::banner_text(a[0]),
            other => panic!("{id}: no port of {other}"),
        };
        assert_eq!(produced, case["value"].as_str().expect("value"), "{id}");
        assert_eq!(
            output::strip_ansi(&produced),
            case["unstyled"].as_str().expect("unstyled"),
            "{id}: stripping must give the plain form click.echo writes"
        );
        checked += 1;
    }
    assert_eq!(checked, 11, "the fixture lost cases");
}

/// Every `kind: "echo"` case: the helpers that print, on both streams.
#[test]
fn styled_lines_match_the_python() {
    let doc = fixture("styled");
    let mut checked = 0;
    for case in cases(&doc) {
        if case["kind"] != "echo" {
            continue;
        }
        let id = case["id"].as_str().expect("id");
        let a = args(case);
        // Which stream a helper writes to is behaviour, not decoration:
        // `step_fail` on stderr is why `agentcage run > log` keeps the
        // red cross. The recorded case says which, and an empty other
        // stream is asserted along with it.
        let (line, on_stderr) = match case["fn"].as_str().expect("fn") {
            "banner" => (output::banner_text(a[0]), false),
            "step_done" => (output::step_done_text(a[0]), false),
            "step_fail" => (output::step_fail_text(a[0]), true),
            "info" => (output::info_text(a[0], a[1]), false),
            "separator" => (output::separator_text(), false),
            other => panic!("{id}: no port of {other}"),
        };
        let (used, unused) = if on_stderr {
            ("err", "out")
        } else {
            ("out", "err")
        };
        assert_eq!(echoed(&line, true), text(case, "color", used), "{id}/color");
        assert_eq!(
            echoed(&line, false),
            text(case, "plain", used),
            "{id}/plain"
        );
        assert_eq!(text(case, "color", unused), "", "{id}: wrong stream");
        checked += 1;
    }
    assert_eq!(checked, 11, "the fixture lost cases");
}

/// Colour only ever adds escapes.
///
/// The invariant PR C5 learned the hard way on the `cage audit` table:
/// the moment a coloured branch pads differently from its plain twin,
/// the two stop being the same layout. Asserted here against the
/// implementation rather than against the fixture, so it holds for
/// inputs the fixture does not carry.
#[test]
fn colour_only_adds_escapes() {
    let samples = [
        output::banner_text("0.40.1"),
        output::banner_text(&"v".repeat(60)),
        output::step_done_text("ok"),
        output::step_fail_text(&output::dim("nested")),
        output::info_text("Name", "web"),
        output::info_text("", ""),
        output::separator_text(),
        output::dim(&output::green(&output::red("three deep"))),
    ];
    for styled in samples {
        let plain = output::strip_ansi(&styled);
        assert!(!plain.contains('\u{1b}'), "an escape survived: {plain:?}");
        // Same visible text, same length in characters, every line.
        for (a, b) in styled.lines().zip(plain.lines()) {
            assert!(
                a.chars().filter(|c| !c.is_control()).count()
                    >= b.chars().filter(|c| !c.is_control()).count()
            );
        }
        assert_eq!(output::strip_ansi(&plain), plain, "stripping is idempotent");
    }
}

// ── timings.json ─────────────────────────────────────────────

fn records(case: &Value) -> Vec<timing::Record> {
    serde_json::from_value(case["records"].clone()).expect("records")
}

/// The `--timings` phase table, and the ledger line behind it.
#[test]
fn timing_output_matches_the_python() {
    let doc = fixture("timings");
    let mut checked = 0;
    for case in cases(&doc) {
        let id = case["id"].as_str().expect("id");
        match case["fn"].as_str().expect("fn") {
            "print_summary" => {
                let lines = timing::summary_lines(&records(case));
                let mut produced = String::new();
                for line in &lines {
                    produced.push_str(line);
                    produced.push('\n');
                }
                assert_eq!(produced, text(case, "plain", "out"), "{id}");
                // The note for an empty ledger goes to stderr, and the
                // table never does.
                let note = text(case, "plain", "err");
                assert_eq!(
                    note.is_empty(),
                    !lines.is_empty(),
                    "{id}: the no-data note and the table are exclusive"
                );
                if !note.is_empty() {
                    assert_eq!(note, "(no timing data for this run)\n", "{id}");
                }
            }
            "phase_echo" => {
                let ms = case["elapsed_ms"].as_f64().expect("elapsed_ms");
                let label = case["label"].as_str().expect("label");
                assert_eq!(
                    format!("{}\n", timing::phase_echo_line(label, ms)),
                    text(case, "plain", "err"),
                    "{id}"
                );
                assert_eq!(text(case, "plain", "out"), "", "{id}: stdout stays clean");
            }
            "ledger_line" => {
                let produced = timing::ledger_line(
                    case["label"].as_str().expect("label"),
                    case["elapsed_ms"].as_f64().expect("elapsed_ms"),
                    case["ts"].as_f64().expect("ts"),
                );
                assert_eq!(produced, case["line"].as_str().expect("line"), "{id}");
                // And it reads back as what it recorded.
                let parsed: timing::Record = serde_json::from_str(&produced).expect("round trip");
                assert_eq!(parsed.label, case["label"].as_str().expect("label"));
            }
            other => panic!("{id}: no port of {other}"),
        }
        checked += 1;
    }
    assert_eq!(checked, 10, "the fixture lost cases");
}

/// The table is never styled, so the two modes are identical.
#[test]
fn the_timing_table_carries_no_escapes() {
    let doc = fixture("timings");
    for case in cases(&doc) {
        if case["kind"] != "echo" {
            continue;
        }
        assert_eq!(case["color"], case["plain"], "{}", case["id"]);
    }
    let lines = timing::summary_lines(&[timing::Record {
        label: "build.egress".to_owned(),
        ms: 1.0,
        ts: 0.0,
    }]);
    assert!(lines.iter().all(|l| !l.contains('\u{1b}')));
}

// ── the fixture itself ───────────────────────────────────────

/// A fixture that no longer bites is worse than none: it reads like
/// coverage. Every case has to be dispatched by one of the tests above,
/// so a `fn` the port has not written fails rather than being skipped.
#[test]
fn every_case_is_claimed_by_a_test() {
    for (name, known) in [
        (
            "styled",
            [
                "dim",
                "green",
                "red",
                "banner_text",
                "banner",
                "step_done",
                "step_fail",
                "info",
                "separator",
            ]
            .as_slice(),
        ),
        (
            "timings",
            ["print_summary", "phase_echo", "ledger_line"].as_slice(),
        ),
    ] {
        let doc = fixture(name);
        assert!(!cases(&doc).is_empty(), "{name} is empty");
        for case in cases(&doc) {
            let f = case["fn"].as_str().expect("every case names a function");
            assert!(known.contains(&f), "{name}/{f} is not dispatched anywhere");
        }
    }
}
