"""On-disk state-compatibility tests against committed Python-written state.

Why these exist
---------------
The host CLI is being rewritten in Rust (``RUST-PORT-PLAN.md`` §2.7). At
cutover, every existing user has cages that the *Python* CLI deployed, and the
Rust binary must read that state **in place, on first run, with no migration
step**. None of it carries a schema version — ``metadata.json`` is a bare
``json.dumps(dict)`` and there is no ``state_version`` field anywhere in
``state.py`` — so there is nothing to branch on. The Rust readers simply have
to accept exactly what the Python writers produce.

``tests/fixtures/state-compat/<version>/`` is a byte-frozen snapshot of that
output, generated by ``scripts/gen-state-fixtures.py``. Everything below loads
those bytes through the real Python readers and asserts **concrete expected
values**, not merely "does not raise". That is deliberate: these assertions are
the specification the Rust implementation will later be held to, and a test
that only proves the parser did not crash proves nothing about the format.

Every test is parametrized over *all* committed generations. A new agentcage
version adds a directory rather than replacing one, so the Rust reader can be
held to several generations of on-disk state at once.
"""

from __future__ import annotations

import gzip
import json
import re
import shutil
import tarfile
from pathlib import Path
from unittest import mock

import pytest
import yaml

FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "state-compat"

#: The cage names the generator emits. Kept in sync via MANIFEST.json, which
#: every generation carries.
RICH = "acme-agent"
MINIMAL = "plain-cage"
APPLE = "mac-agent"

#: The stand-in home the generator scrubs every real path down to.
SCRUB_HOME = "/home/agentcage-fixture"


def _generations() -> list[str]:
    if not FIXTURE_ROOT.is_dir():
        return []
    return sorted(p.name for p in FIXTURE_ROOT.iterdir() if p.is_dir())


GENERATIONS = _generations()

pytestmark = pytest.mark.skipif(
    not GENERATIONS, reason="no state-compat fixtures committed"
)


@pytest.fixture(params=GENERATIONS or [None], ids=lambda v: f"gen-{v}")
def generation(request) -> Path:
    """One committed fixture generation, as a directory path."""
    return FIXTURE_ROOT / request.param


@pytest.fixture
def state(generation, tmp_path, monkeypatch):
    """``agentcage.state`` pointed at a throwaway copy of *generation*.

    A copy rather than the committed tree itself: several readers
    (``capture_dir``, ``grants_dir``, ``cage_data_dir``) ``mkdir`` on the way
    in, and a test run must not mutate a committed fixture.
    """
    import agentcage.state as _state

    shutil.copytree(generation / "xdg-config", tmp_path / "config")
    shutil.copytree(generation / "xdg-data", tmp_path / "data")

    monkeypatch.setattr(_state, "_CONFIG_DIR", tmp_path / "config" / "agentcage")
    monkeypatch.setattr(
        _state, "_DEPLOYMENTS_DIR", tmp_path / "config" / "agentcage" / "cages"
    )
    monkeypatch.setattr(_state, "_DATA_DIR", tmp_path / "data" / "agentcage")
    return _state


# ── The fixture itself ─────────────────────────────────────


def test_generation_is_stamped_with_its_version(generation):
    """The directory name is the agentcage version that produced it."""
    manifest = json.loads((generation / "MANIFEST.json").read_text())
    assert manifest["agentcage_version"] == generation.name
    assert manifest["generator"] == "scripts/gen-state-fixtures.py"
    assert manifest["cages"] == {"rich": RICH, "minimal": MINIMAL, "apple": APPLE}


def test_manifest_lists_every_file_present(generation):
    on_disk = sorted(
        str(p.relative_to(generation))
        for p in generation.rglob("*")
        if p.is_file() and p.name != "MANIFEST.json"
    )
    manifest = json.loads((generation / "MANIFEST.json").read_text())
    assert manifest["files"] == on_disk


def test_fixture_carries_no_real_secrets_and_no_local_paths(generation):
    """A regression guard on the fixture, not on any reader.

    Every secret-shaped value is an obviously-fake ``TEST-NOT-A-REAL-*``
    string, and no path from the generating machine survives the scrub. The
    tarball is decompressed first — gzip would hide a leak from a raw scan.
    """
    forbidden = ("/Users/", "/tmp/agentcage-state-fixture-")
    # ``/home/node`` and ``/home/acproxy`` are paths *inside* the workload and
    # egress containers, not host paths.
    allowed_homes = {"agentcage-fixture", "node", "acproxy"}
    for path in sorted(generation.rglob("*")):
        if not path.is_file():
            continue
        blob = path.read_bytes()
        if path.suffix == ".gz":
            blob = gzip.decompress(blob)
        text = blob.decode("utf-8", "replace")
        for needle in forbidden:
            assert needle not in text, f"{path.name} leaks {needle!r}"
        found = set(re.findall(r"/home/([A-Za-z0-9._-]+)", text))
        assert found <= allowed_homes, f"{path.name} leaks home dirs: {found}"


# ── state.load_raw_config ──────────────────────────────────


def test_load_raw_config_rich(state):
    raw = state.load_raw_config(RICH)

    assert raw["name"] == RICH
    assert raw["isolation"] == "container"
    assert raw["lifecycle"] == "service"
    assert raw["scaffold"] == "claude-code"
    assert raw["container"]["image"] == "docker.io/library/node:22-slim"
    assert raw["container"]["command"] == ["node", "/app/agent.js"]
    assert raw["container"]["named_volumes"] == {
        "acme-agent-npm": "/home/node/.npm:rw"
    }
    assert raw["dns_servers"] == ["1.1.1.1", "9.9.9.9"]
    assert raw["domains"]["mode"] == "allowlist"
    assert raw["domains"]["allow"] == [
        "api.anthropic.com",
        "github.com",
        "*.githubusercontent.com",
        "registry.npmjs.org",
        "openrouter.ai",
    ]
    assert raw["domains"]["block"] == ["telemetry.example.com"]
    assert raw["domains"]["passthrough"] == ["pinned-api.example.com"]
    assert raw["domains"]["expires"] == {
        "temp-download.example.com": "2026-09-08T18:00:00Z"
    }
    assert raw["ports"]["tcp"]["allow"] == [80, 443, 993]
    assert raw["ports"]["icmp"]["allow"] is False
    assert raw["max_request_body"] == 10485760
    assert raw["exec_aliases"] == {"claude": ["claude", "--print"]}


def test_load_raw_config_key_order_is_preserved(state):
    """``save_raw_config`` dumps with ``sort_keys=False``.

    cage.yaml key order is user-visible after ``cage edit``, so a Rust
    emitter has to preserve it too (plan §5, Phase 0).
    """
    raw = state.load_raw_config(RICH)
    assert list(raw)[:6] == [
        "name", "isolation", "lifecycle", "scaffold", "container", "dns_servers",
    ]


def test_load_raw_config_secret_injection_shapes(state):
    """Three rules, three different secret sources, one minted placeholder."""
    rules = state.load_raw_config(RICH)["secret_injection"]
    assert [r["env"] for r in rules] == [
        "ANTHROPIC_API_KEY", "GITHUB_TOKEN", "IMAP_PASSWORD",
    ]
    assert rules[0]["source"] == "systemd-creds:ANTHROPIC_API_KEY"
    assert rules[0]["inject_headers"] == ["x-api-key"]
    assert rules[0]["inject_body"] is False
    assert rules[1]["source"] == "env:FIXTURE_GITHUB_TOKEN"
    assert rules[1]["inject_to"] == ["github.com", "*.githubusercontent.com"]
    # This rule omitted ``placeholder:`` in the operator's file;
    # ``fill_placeholders`` minted one and rewrote cage.yaml. The token must
    # be present, prefixed, and carry 32 hex characters of entropy.
    minted = rules[2]["placeholder"]
    assert minted.startswith("agentcage:secret:IMAP_PASSWORD:")
    suffix = minted.rsplit(":", 1)[1]
    assert len(suffix) == 32 and int(suffix, 16) >= 0
    assert "source" not in rules[2]


def test_load_raw_config_protocol_relay(state):
    relay = state.load_raw_config(RICH)["protocol_relays"][0]
    assert relay["name"] == "mail"
    assert relay["type"] == "imap"
    assert relay["listen"] == "0.0.0.0:1143"
    assert relay["upstream"] == {
        "host": "imap.example.com",
        "port": 993,
        "tls": True,
        "tls_servername": "imap.example.com",
        "ca_file": "~/fixture-ca.pem",
    }
    assert relay["policy"]["write_mode"] == "organise"
    assert relay["policy"]["folder_allowlist"] == ["INBOX", "Archive"]
    assert relay["auth"]["password_source"] == "systemd-creds:IMAP_PASSWORD"


def test_load_raw_config_agents(state):
    agents = state.load_raw_config(RICH)["agents"]
    assert agents["decider"]["enable"] is True
    assert agents["decider"]["provider"] == "openrouter"
    assert agents["decider"]["model"] == "z-ai/glm-5.3"
    assert agents["decider"]["api_key"] == "systemd-creds:OPENROUTER_API_KEY"
    assert agents["watcher"]["auto_revoke"] is True
    assert agents["watcher"]["max_digest_tokens"] == 8000


def test_load_raw_config_minimal(state):
    """A cage whose config sets almost nothing still round-trips."""
    raw = state.load_raw_config(MINIMAL)
    assert raw == {
        "name": MINIMAL,
        "container": {"image": "localhost/plain:latest"},
        "dns_servers": ["1.1.1.1"],
    }


def test_list_deployments(state):
    assert state.list_deployments() == sorted([RICH, APPLE, MINIMAL])


def test_load_deployment_config_parses_to_a_full_config(state):
    """The full validating parser, not just the raw YAML reader."""
    cfg = state.load_deployment_config(RICH)

    assert cfg.name == RICH
    assert cfg.isolation == "container"
    assert cfg.scaffold == "claude-code"
    assert cfg.dns_servers == ["1.1.1.1", "9.9.9.9"]
    assert cfg.domains.mode == "allowlist"
    assert cfg.domains.block == ["telemetry.example.com"]
    assert cfg.ports.tcp.allow == [80, 443, 993]
    assert cfg.secrets.backend == "systemd-creds"
    assert cfg.secrets.scope == "user"
    assert cfg.secrets.allow_plaintext is False
    assert [r.env for r in cfg.secret_injection] == [
        "ANTHROPIC_API_KEY", "GITHUB_TOKEN", "IMAP_PASSWORD",
    ]
    assert cfg.capture.enable_har is True
    assert cfg.capture.exclude_domains == ["registry.npmjs.org"]
    assert cfg.agents.decider.enable is True
    assert cfg.agents.watcher.max_flows == 100

    relay = cfg.protocol_relays[0]
    assert (relay.name, relay.type, relay.listen) == ("mail", "imap", "0.0.0.0:1143")
    assert relay.upstream.host == "imap.example.com"
    assert relay.upstream.port == 993
    assert relay.upstream.tls is True
    assert relay.policy.write_mode == "organise"


# ── state.load_metadata ────────────────────────────────────


def test_load_metadata_rich(state, generation):
    """``metadata.json`` is a bare ``json.dumps(dict)`` — no version field."""
    meta = state.load_metadata(RICH)
    assert meta == {
        "agentcage_version": generation.name,
        "scaffold": "claude-code",
        "network_octet": 137,
    }
    assert "state_version" not in meta


def test_load_metadata_minimal_has_no_scaffold(state, generation):
    meta = state.load_metadata(MINIMAL)
    assert meta["agentcage_version"] == generation.name
    assert "scaffold" not in meta


def test_load_metadata_missing_returns_empty(state):
    assert state.load_metadata("no-such-cage") == {}


def test_metadata_json_is_compact_single_line(state):
    """Written by ``json.dumps(metadata)`` — no indent, no trailing newline."""
    raw = (state.deployment_dir(RICH) / "metadata.json").read_text()
    assert raw.startswith('{"agentcage_version":')
    assert "\n" not in raw


# ── fingerprint.json ───────────────────────────────────────


def test_load_fingerprint(state):
    from agentcage.fingerprint import FINGERPRINT_VERSION, fingerprint_matches

    fp = state.load_fingerprint(RICH)
    assert fp is not None
    assert fp["version"] == FINGERPRINT_VERSION == 1
    assert sorted(fp["components"]) == [
        "cage_yaml", "image_digests", "resolved_config",
        "scaffold_version", "units",
    ]
    assert all(len(v) == 64 for v in fp["components"].values())
    assert len(fp["fingerprint"]) == 64
    assert fingerprint_matches(fp, fp)


def test_fingerprint_json_is_indented_and_sorted(state):
    """``save_fingerprint`` uses ``indent=2, sort_keys=True`` + a newline."""
    raw = (state.deployment_dir(RICH) / "fingerprint.json").read_text()
    assert raw.endswith("}\n")
    assert raw.splitlines()[1].startswith('  "components"')


def test_minimal_cage_has_no_fingerprint(state):
    """A never-deployed cage has no fingerprint; the reader must say None."""
    assert state.load_fingerprint(MINIMAL) is None


# ── grants overlay ─────────────────────────────────────────


def test_load_grants(state):
    """The overlay is ``grants/grants.yaml`` — a YAML *list*, not JSON."""
    assert state.grants_file(RICH).name == "grants.yaml"

    grants = state.load_grants(RICH)
    assert grants == [
        {
            "domain": "files.pythonhosted.org",
            "granted_at": "2026-03-14T15:00:00+00:00",
            "expires_at": "2026-03-14T16:00:00+00:00",
            "reason": "pip install requested by the decider",
            "source": "policy-hook",
        },
        {
            "domain": "objects.githubusercontent.com",
            "granted_at": "2026-03-14T15:04:00+00:00",
            "expires_at": "",
            "reason": "release asset download",
            "source": "operator",
        },
    ]
    # An empty ``expires_at`` means "no expiry", not "expired".
    assert grants[1]["expires_at"] == ""


def test_load_grants_absent_is_empty(state):
    assert state.load_grants(MINIMAL) == []


def test_policy_audit_jsonl(state):
    """One JSON object per line, each stamped with a UTC ISO ``ts``."""
    lines = state.policy_audit_file(RICH).read_text().splitlines()
    entries = [json.loads(line) for line in lines]
    assert [e["kind"] for e in entries] == [
        "policy_grant_applied", "policy_grant_removed",
    ]
    assert entries[0]["domain"] == "files.pythonhosted.org"
    assert entries[0]["ts"] == "2026-03-14T15:09:26+00:00"
    assert list(entries[0])[0] == "ts", "ts is prepended, not appended"
    # It must NOT live inside grants/ — that directory is container-writable.
    assert state.policy_audit_file(RICH).parent == state.grants_dir(RICH).parent


# ── secret stores ──────────────────────────────────────────


def test_secret_key_index(state):
    """``secret_keys.json`` is the keychain backend's non-secret name index."""
    from agentcage.secret_store import KeychainStore

    store = KeychainStore()
    assert store.names(RICH, state_dir=state.deployment_dir(RICH)) == [
        "ANTHROPIC_API_KEY", "GITHUB_TOKEN",
    ]
    assert store.names(APPLE, state_dir=state.deployment_dir(APPLE)) == [
        "ANTHROPIC_API_KEY", "OPENROUTER_API_KEY",
    ]
    # A JSON array of strings, sorted.
    raw = json.loads(
        (state.deployment_dir(RICH) / "secret_keys.json").read_text()
    )
    assert raw == sorted(raw) and all(isinstance(k, str) for k in raw)


def test_secret_key_index_absent_is_empty(state):
    from agentcage.secret_store import KeychainStore

    assert KeychainStore().names(
        MINIMAL, state_dir=state.deployment_dir(MINIMAL)
    ) == []


def test_pending_secrets_is_a_list_of_pairs(state):
    """``pending_secrets.json`` is ``[[key, value], …]`` — not an object.

    Both writers agree on this: ``ApplePlaintextStore._save`` and the VM
    hand-off in ``cli.py``. A Rust reader that assumed a JSON map would fail
    on every cage that has ever used either path.
    """
    from agentcage.secret_store import ApplePlaintextStore

    raw = json.loads(
        (state.deployment_dir(RICH) / "pending_secrets.json").read_text()
    )
    assert isinstance(raw, list)
    assert raw == [["GITHUB_TOKEN", "TEST-NOT-A-REAL-SECRET-0003"]]

    store = ApplePlaintextStore()
    d = state.deployment_dir(RICH)
    assert store.names(RICH, state_dir=d) == ["GITHUB_TOKEN"]
    assert store.get(RICH, "GITHUB_TOKEN", state_dir=d) == (
        "TEST-NOT-A-REAL-SECRET-0003"
    )
    assert store.get(RICH, "NOPE", state_dir=d) is None


def test_cred_blobs_presence_and_shape_only(state):
    """``creds/<key>.cred`` — shape only; the contents cannot be decrypted.

    systemd-creds encryption is host-bound (host key / TPM2 / per-user key),
    so this blob is opaque everywhere except the machine that made it. The
    Rust port has the same obligation the Python has: find the file, hand it
    to ``systemd-creds decrypt``, never parse it.
    """
    creds = state.deployment_dir(RICH) / "creds"
    assert sorted(p.name for p in creds.iterdir()) == [
        "ANTHROPIC_API_KEY.cred", "IMAP_PASSWORD.cred", "OPENROUTER_API_KEY.cred",
    ]
    blob = (creds / "ANTHROPIC_API_KEY.cred").read_bytes()
    assert len(blob) > 64
    # base64 armor, as ``systemd-creds encrypt … -`` emits it.
    assert blob.decode().replace("\n", "").isalnum() or b"/" in blob


# ── derived artifacts ──────────────────────────────────────


def test_proxy_config_holds_only_the_whitelisted_keys(state):
    """``save_proxy_config`` strips everything the addon does not read."""
    path = state.deployment_dir(RICH) / "proxy-config.yaml"
    cfg = yaml.safe_load(path.read_text())

    assert set(cfg) <= set(state._PROXY_KEYS) | {"agentcage_version"}
    # The keys the proxy must never see.
    for leaked in ("container", "dns_servers", "name", "isolation", "ports"):
        assert leaked not in cfg
    assert cfg["domains"]["allow"][0] == "api.anthropic.com"
    assert cfg["capture"]["enable_har"] is True
    assert cfg["agents"]["decider"]["model"] == "z-ai/glm-5.3"


def test_proxy_config_inlines_the_relay_ca(state, generation):
    """``ca_file`` is read at deploy time and becomes ``ca_pem``."""
    cfg = yaml.safe_load(
        (state.deployment_dir(RICH) / "proxy-config.yaml").read_text()
    )
    upstream = cfg["protocol_relays"][0]["upstream"]
    assert "ca_file" not in upstream, "the host path must not reach the proxy"
    assert upstream["ca_pem"].startswith("-----BEGIN CERTIFICATE-----")
    assert "TEST-NOT-A-REAL-CERTIFICATE-0001" in upstream["ca_pem"]
    # The version stamp the Policy API reports when AGENTCAGE_VERSION is unset.
    assert cfg["agentcage_version"] == generation.name


def test_proxy_config_of_a_defaulted_cage_is_just_the_version(state, generation):
    cfg = yaml.safe_load(
        (state.deployment_dir(MINIMAL) / "proxy-config.yaml").read_text()
    )
    assert cfg == {"agentcage_version": generation.name}


def test_placeholders_env(state):
    """``ENV=PLACEHOLDER`` lines, one per rule that has a placeholder."""
    text = state.placeholders_env_path(RICH).read_text()
    lines = text.splitlines()
    assert len(lines) == 3
    assert text.endswith("\n")
    envs = [line.split("=", 1)[0] for line in lines]
    assert envs == ["ANTHROPIC_API_KEY", "GITHUB_TOKEN", "IMAP_PASSWORD"]
    for line in lines:
        env, placeholder = line.split("=", 1)
        assert placeholder.startswith(f"agentcage:secret:{env}:")
    assert lines[0].endswith(":aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")


def test_placeholders_env_is_empty_when_nothing_is_injected(state):
    assert state.placeholders_env_path(MINIMAL).read_text() == ""


def test_dns_allowlist(state):
    """dnsmasq ``--servers-file`` format: one line per (domain × upstream)."""
    lines = state.dns_allowlist_path(RICH).read_text().splitlines()
    assert lines[:4] == [
        "server=/api.anthropic.com/1.1.1.1",
        "server=/api.anthropic.com/9.9.9.9",
        "server=/github.com/1.1.1.1",
        "server=/github.com/9.9.9.9",
    ]
    # The relay upstream is allowlisted too, and blocked domains are not.
    assert "server=/imap.example.com/1.1.1.1" in lines
    assert not any("telemetry.example.com" in line for line in lines)
    assert len(lines) == 14


def test_quadlets(generation):
    """The unit files Python installed and systemd is still running."""
    units = generation / "xdg-config" / "containers" / "systemd"
    assert sorted(p.name for p in units.iterdir()) == [
        "acme-agent-cage.container",
        "acme-agent-certs.volume",
        "acme-agent-egress.container",
        "acme-agent-net.network",
        "acme-agent-public-certs.volume",
    ]
    cage = (units / "acme-agent-cage.container").read_text()
    assert "ContainerName=acme-agent-cage" in cage
    assert "Image=docker.io/library/node:22-slim" in cage
    # The pinned subnet: metadata.json's network_octet is 137.
    assert "Network=acme-agent-net.network:ip=10.89.137.2" in cage
    assert f'Environment="AGENTCAGE_VERSION={generation.name}"' in cage
    assert (
        f"EnvironmentFile={SCRUB_HOME}/.config/agentcage/cages/acme-agent"
        "/cage-env/placeholders.env" in cage
    )

    egress = (units / "acme-agent-egress.container").read_text()
    assert f"Image=localhost/agentcage-egress:{generation.name}" in egress
    # The .cred blobs are decrypted into podman secrets at unit start.
    assert 'systemd-creds --user decrypt --name "ANTHROPIC_API_KEY"' in egress
    # Runtime secrets stage under %t (XDG_RUNTIME_DIR), never a literal uid.
    assert "%t/agentcage/acme-agent/secrets" in egress


def test_patches_dir_holds_per_cage_resolv_files(generation):
    """A *shared* data-dir location, not a per-cage one."""
    patches = generation / "xdg-data" / "agentcage" / "patches"
    assert sorted(p.name for p in patches.iterdir()) == [
        "resolv-acme-agent.conf", "resolv-egress-acme-agent.conf",
    ]
    cage_resolv = (patches / "resolv-acme-agent.conf").read_text()
    assert "nameserver 10.89.137.10" in cage_resolv
    egress_resolv = (patches / "resolv-egress-acme-agent.conf").read_text()
    assert "nameserver 1.1.1.1" in egress_resolv
    assert "nameserver 9.9.9.9" in egress_resolv


# ── egress-written logs ────────────────────────────────────


def test_capture_jsonl_round_trips_through_the_har_builder(state):
    from agentcage.har import capture_to_har

    lines = state.capture_file(RICH).read_text().splitlines()
    entries = [json.loads(line) for line in lines]
    assert len(entries) == 2

    first = entries[0]
    assert first["flow_id"] == "fixture-flow-0001"
    assert first["decision"] == "allowed"
    assert first["host"] == "api.anthropic.com"
    assert first["direction"] == "outbound"
    # Headers are [name, value] pairs, and both perspectives are recorded:
    # inbound keeps the placeholder, outbound has the wire value.
    inbound_headers = dict(map(tuple, first["inbound"]["request"]["headers"]))
    outbound_headers = dict(map(tuple, first["outbound"]["request"]["headers"]))
    assert inbound_headers["x-api-key"].startswith(
        "agentcage:secret:ANTHROPIC_API_KEY:"
    )
    assert outbound_headers["x-api-key"] == "TEST-NOT-A-REAL-SECRET-0001"

    assert entries[1]["decision"] == "blocked"
    assert entries[1]["inspectors"][0]["name"] == "domain"
    assert entries[1]["outbound"]["response"] == {}

    har = capture_to_har(entries, view="inbound")
    assert har["log"]["version"] == "1.2"
    assert len(har["log"]["entries"]) == 2
    assert har["log"]["entries"][0]["request"]["url"] == (
        "https://api.anthropic.com/v1/messages"
    )
    assert har["log"]["entries"][0]["response"]["status"] == 200

    outbound_har = capture_to_har(entries, view="outbound")
    hdrs = {
        h["name"]: h["value"]
        for h in outbound_har["log"]["entries"][0]["request"]["headers"]
    }
    assert hdrs["x-api-key"] == "TEST-NOT-A-REAL-SECRET-0001"


def test_apple_container_state_root_and_audit_jsonl(generation):
    """apple-container keeps runtime state in a third, separate root.

    ``~/.config/agentcage/apple-container/<name>/logs/`` — NOT under the
    deployments dir and not under ``$XDG_DATA_HOME``. On container and vm
    backends there is no host-side ``audit.jsonl`` at all; the addon writes
    to stderr and the host reads it back from journalctl.
    """
    from agentcage.audit import AuditEntry, compute_summary, extract_audit_json

    logs = (
        generation / "xdg-config" / "agentcage" / "apple-container"
        / APPLE / "logs"
    )
    assert sorted(p.name for p in logs.iterdir()) == [
        "audit.jsonl", "capture.jsonl", "dnsmasq.log", "ready",
    ]
    # No audit.jsonl beside the container backend's capture dir.
    assert not (
        generation / "xdg-data" / "agentcage" / RICH / "audit.jsonl"
    ).exists()

    raw = [
        extract_audit_json(line)
        for line in (logs / "audit.jsonl").read_text().splitlines()
    ]
    assert all(d is not None for d in raw)
    entries = [AuditEntry.from_dict(d) for d in raw]

    assert [e.decision for e in entries] == ["allowed", "blocked", "flagged"]
    assert [e.host for e in entries] == [
        "api.anthropic.com", "telemetry.example.com", "github.com",
    ]
    assert entries[0].ts == "2026-03-14T15:09:26+00:00"
    assert entries[0].secrets_injected == ["ANTHROPIC_API_KEY"]
    assert entries[0].port == 443
    assert entries[1].reason == "domain not in allowlist"
    assert entries[1].inspectors[0]["severity"] == "high"
    assert entries[2].secrets_redacted == ["GITHUB_TOKEN"]
    assert entries[2].source == "relay"

    summary = compute_summary(entries)
    assert summary["total"] == 3
    assert summary["decisions"]["allowed"] == 1
    assert summary["decisions"]["blocked"] == 1
    assert summary["decisions"]["flagged"] == 1


# ── backup tarball ─────────────────────────────────────────


def _tarball(generation: Path) -> Path:
    (path,) = (generation / "backup").iterdir()
    return path


def test_backup_tarball_structure(generation):
    with tarfile.open(_tarball(generation), "r:gz") as tar:
        names = sorted(m.name for m in tar.getmembers())
        manifest = json.loads(
            tar.extractfile("agentcage-backup/manifest.json").read()
        )

    assert names == [
        "agentcage-backup/capture",
        "agentcage-backup/capture/capture.jsonl",
        "agentcage-backup/config",
        "agentcage-backup/config/cage.yaml",
        "agentcage-backup/config/metadata.json",
        "agentcage-backup/config/proxy-config.yaml",
        "agentcage-backup/manifest.json",
        "agentcage-backup/secrets",
        "agentcage-backup/secrets/ANTHROPIC_API_KEY",
        "agentcage-backup/secrets/GITHUB_TOKEN",
        "agentcage-backup/secrets/IMAP_PASSWORD",
        "agentcage-backup/volumes",
    ]
    assert manifest == {
        "format_version": 1,
        "agentcage_version": generation.name,
        "cage_name": RICH,
        "isolation": "container",
        "timestamp": "2026-03-14T15:09:26+00:00",
        "has_secrets": True,
        "has_capture": True,
        "named_volumes": [],
        # From _expected_secrets(cfg): the three injection rules plus the
        # agents' shared api_key, sorted — NOT just what was in the store.
        "secret_keys": [
            "ANTHROPIC_API_KEY", "GITHUB_TOKEN", "IMAP_PASSWORD",
            "OPENROUTER_API_KEY",
        ],
        "secrets_included": True,
    }


def test_backup_secret_files_are_bare_values(generation):
    with tarfile.open(_tarball(generation), "r:gz") as tar:
        value = tar.extractfile(
            "agentcage-backup/secrets/ANTHROPIC_API_KEY"
        ).read().decode()
    assert value == "TEST-NOT-A-REAL-SECRET-0001"


def test_cage_restore_of_the_fixture_tarball(generation, tmp_path, monkeypatch):
    """``cage restore --no-start`` rebuilds a full state dir from the tarball.

    This is the D11 acceptance path: the Rust implementation has to restore a
    tarball a *Python* agentcage produced.
    """
    from click.testing import CliRunner

    import agentcage.cli as cli
    import agentcage.state as _state

    home = tmp_path / "home"
    (home / ".config" / "agentcage").mkdir(parents=True)
    # The restored cage.yaml declares ``upstream.ca_file: ~/fixture-ca.pem``,
    # which save_proxy_config reads and inlines. Provide it under the fake
    # home rather than weakening the test by stubbing the resolver out.
    (home / "fixture-ca.pem").write_text(
        "-----BEGIN CERTIFICATE-----\n"
        "TEST-NOT-A-REAL-CERTIFICATE-0001\n"
        "-----END CERTIFICATE-----\n"
    )
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setattr(
        _state, "_CONFIG_DIR", home / ".config" / "agentcage"
    )
    monkeypatch.setattr(
        _state, "_DEPLOYMENTS_DIR", home / ".config" / "agentcage" / "cages"
    )
    monkeypatch.setattr(
        _state, "_DATA_DIR", home / ".local" / "share" / "agentcage"
    )

    podman = mock.MagicMock()
    podman.secret_exists.return_value = False

    with mock.patch.object(cli, "_podman_for_cage", return_value=podman):
        result = CliRunner().invoke(
            cli.main,
            ["cage", "restore", str(_tarball(generation)),
             "--name", "restored", "--no-start"],
        )

    assert result.exit_code == 0, result.output
    assert "Cage state restored" in result.output

    # Secrets were included, so they are pushed back into the podman store.
    created = {c.args[0]: c.args[1] for c in podman.secret_create.call_args_list}
    assert created == {
        "restored.ANTHROPIC_API_KEY": "TEST-NOT-A-REAL-SECRET-0001",
        "restored.GITHUB_TOKEN": "TEST-NOT-A-REAL-SECRET-0003",
        "restored.IMAP_PASSWORD": "TEST-NOT-A-REAL-SECRET-0004",
    }

    # State dir rebuilt, with the name rewritten and derived files regenerated.
    assert _state.deployment_exists("restored")
    raw = _state.load_raw_config("restored")
    assert raw["name"] == "restored"
    assert raw["domains"]["allow"][0] == "api.anthropic.com"
    assert _state.load_metadata("restored")["agentcage_version"] == generation.name

    proxy = yaml.safe_load(
        (_state.deployment_dir("restored") / "proxy-config.yaml").read_text()
    )
    assert "container" not in proxy
    assert proxy["protocol_relays"][0]["upstream"]["ca_pem"].startswith(
        "-----BEGIN CERTIFICATE-----"
    )
    dns = _state.dns_allowlist_path("restored").read_text().splitlines()
    assert "server=/api.anthropic.com/1.1.1.1" in dns


# ── the fixture must survive a fresh checkout ──────────────


def test_fixture_has_no_empty_directories(generation):
    """git cannot represent an empty directory.

    One that the generator emitted would live on in the author's working tree,
    be silently dropped by ``git add``, and then make the regeneration check
    below fail on every fresh checkout while passing locally. This test fails
    on the generating machine — which is the only place it can be fixed.
    """
    empty = sorted(
        str(d.relative_to(generation))
        for d in generation.rglob("*")
        if d.is_dir() and not any(d.iterdir())
    )
    assert empty == [], (
        "these directories cannot be committed and will make CI diverge "
        "from a local run"
    )


def test_every_fixture_file_is_tracked_by_git():
    """The same trap as empty directories, for files.

    A fixture file that exists locally but was never ``git add``-ed passes
    every local check and is simply absent on CI. Compare what is on disk
    against what git actually has.
    """
    import subprocess

    repo = Path(__file__).parent.parent
    try:
        listed = subprocess.run(
            ["git", "ls-files", "-z", "--", "tests/fixtures/state-compat"],
            cwd=repo, capture_output=True, text=True,
        )
    except OSError:  # pragma: no cover — git not installed
        pytest.skip("git is not available")
    if listed.returncode != 0:  # pragma: no cover — not a git checkout
        pytest.skip("not a git checkout")

    tracked = {p for p in listed.stdout.split("\0") if p}
    on_disk = {
        str(p.relative_to(repo))
        for p in (FIXTURE_ROOT).rglob("*") if p.is_file()
    }
    assert on_disk - tracked == set(), "untracked fixture files"
    assert tracked - on_disk == set(), "tracked fixture files missing on disk"


def _package_version() -> str | None:
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("agentcage")
    except PackageNotFoundError:  # pragma: no cover — uninstalled checkout
        return None


@pytest.mark.skipif(
    _package_version() is None,
    reason="agentcage is not installed; the generator cannot stamp a version",
)
def test_generator_reproduces_the_committed_fixture_byte_for_byte():
    """Re-running the generator must produce an identical tree.

    Determinism is the whole point: a fixture that drifts on every run is
    worthless as a format specification. This is also the guard that catches
    a writer change landing without a fixture regeneration.

    Only the generation matching the *installed* version is checked — older
    generations are snapshots of code that no longer exists here.

    On failure the generator prints a per-file report (added / removed /
    changed, with a unified diff, and for the backup tarball a comparison of
    decompressed members rather than the gzip stream). It is relayed verbatim
    so a CI log is enough to diagnose the drift without reproducing it.
    """
    import subprocess
    import sys

    version = _package_version()
    if version not in GENERATIONS:
        # The stamp comes from importlib.metadata, which after PR A1 resolves
        # from the root VERSION file. A version bump is therefore expected to
        # land here exactly once, and the fix is to add a generation rather
        # than to edit an existing one.
        pytest.skip(
            f"no committed fixture for the installed version {version}; "
            f"committed generations are {GENERATIONS}. If the version was "
            f"just bumped, add a generation:\n"
            f"    uv run python scripts/gen-state-fixtures.py"
        )

    repo = Path(__file__).parent.parent
    result = subprocess.run(
        [sys.executable, str(repo / "scripts" / "gen-state-fixtures.py"), "--check"],
        capture_output=True,
        text=True,
        cwd=repo,
    )
    assert result.returncode == 0, (
        "\n\nThe committed fixture no longer matches what the generator "
        "produces.\nIf the change is intended, re-run:\n"
        "    uv run python scripts/gen-state-fixtures.py\n\n"
        + result.stderr
        + "\n"
        + result.stdout
    )
