//! agentcage's on-disk state, and the systemd unit lifecycle on top of
//! it.
//!
//! The port of `src/agentcage/state.py` and `src/agentcage/systemd.py`
//! (RUST-PORT-PLAN.md, Track D, PR D2).
//!
//! # The problem this crate exists to solve
//!
//! At cutover, every existing user has cages that the *Python* CLI
//! deployed, and the Rust binary has to read that state in place, on
//! its first invocation, with no migration step. None of it carries a
//! schema version — `metadata.json` is a bare `json.dumps(dict)` and
//! there is no `state_version` field anywhere in `state.py` — so there
//! is nothing to branch on. These readers simply have to accept
//! exactly what the Python writers produced.
//!
//! "Exactly what the Python writers produced" is not a judgement call
//! here: PR A7 committed a byte-frozen snapshot of it at
//! `tests/fixtures/state-compat/0.40.1/`, generated by driving the
//! real code paths for three cages, and `tests/state_compat.rs` reads
//! every file in it and asserts concrete values. That fixture is the
//! specification; this crate is held to it.
//!
//! # Layout
//!
//! | module | Python | what it owns |
//! | :-- | :-- | :-- |
//! | [`paths`] | `state.py`'s module constants | the **four** state roots and every path derived from them |
//! | [`atomic`] | `_atomic_write_text` | `O_EXCL` + PID-suffixed temp + one retry, and why it never unlinks |
//! | [`deployment`] | `save_deployment` … `fill_placeholders` | the stored `cage.yaml` |
//! | [`metadata`] | `save_metadata`, `save_fingerprint` | the two JSON files, which disagree about everything |
//! | [`derived`] | `save_proxy_config`, `save_placeholders_env`, `save_dns_allowlist` | the files regenerated on every deploy |
//! | [`grants`] | `load_grants`, `save_grants`, `append_policy_audit` | the Policy-API overlay and its audit trail |
//! | [`pending_secrets`] | — | the *format* of `pending_secrets.json` and `secret_keys.json`; the stores are D3's |
//! | [`systemd`] | `systemd.py`, `install_units` | which directory a unit file belongs in, and the reload after |
//! | [`pyfs`] | `os.path.expanduser` / `expandvars` | the two path functions with a leave-it-alone branch |
//!
//! Most of the API is methods on [`Paths`], one per Python free
//! function and with the same name, so `state.load_raw_config(name)`
//! reads as `paths.load_raw_config(name)`.
//!
//! # Three things §2.7 gets subtly right and a reader will get wrong
//!
//! 1. The per-cage config directory is `.../agentcage/**cages**/<name>/`.
//! 2. The grants overlay is `grants/grants.**yaml**` — a top-level
//!    YAML **list**, not a JSON object.
//! 3. `pending_secrets.json` is a JSON array of `[key, value]`
//!    **pairs**, not an object.
//!
//! And two absences:
//!
//! * There is **no host-side `audit.jsonl`** for a `container` or `vm`
//!   cage. Only apple-container has one, at
//!   [`Paths::apple_audit_file`]; elsewhere the addon writes to stderr
//!   and the host reads `journalctl`.
//! * The apple-container root **ignores `XDG_CONFIG_HOME`** and
//!   expands `~` directly, so an XDG sandbox does not redirect it.
//!   [`Paths::under`] moves `HOME` too, for exactly this reason.
//!
//! # What is NOT in here
//!
//! Anything that decides *whether* to write. `cage update`'s
//! fingerprint comparison, the grants reconcile's promote/revoke
//! logic, the backup tarball — those are D6-D12, and they take a
//! [`Paths`] rather than reaching for a global.

pub mod atomic;
pub mod deployment;
pub mod derived;
pub mod error;
pub mod grants;
pub mod metadata;
pub mod paths;
pub mod pending_secrets;
pub mod pyfs;
pub mod systemd;
pub mod testdir;

pub use atomic::{atomic_write_text, atomic_write_text_as};
pub use deployment::{AgentSchema, mint_placeholder};
pub use derived::PROXY_KEYS;
pub use error::{Result, StateError};
pub use metadata::{dumps_fingerprint, dumps_metadata};
pub use paths::Paths;
pub use systemd::{Installed, QUADLET_SUFFIXES, Units};
pub use testdir::TestDir;
