"""``python -m agentcage`` — the Python CLI, without a console script.

This module is how the Python implementation is invoked after the Rust
cutover, and the reason it exists is that ``[project.scripts]`` no
longer does.

``pyproject.toml`` used to install an ``agentcage`` command. Keeping it
would mean a ``pip install`` could put a *second*, older implementation
on ``PATH`` ahead of the real binary, with no indication which one an
operator was talking to — the failure would look like agentcage
behaving differently on one machine, not like two programs. So the
console script is gone (RUST-PORT-PLAN.md §2.4), and the package is
dev/test-only.

But the Python is not dead code: it is the **oracle**. Every fixture
under ``tests/fixtures/`` is generated by running it, and
``tests/e2e/run.sh`` runs the whole end-to-end suite against both
implementations so they can be compared phase by phase. That needs a
way to invoke it, and a module entry point is the honest one — it
cannot be reached by accident, only by asking for it by name.

``tests/e2e/python-cli`` is the wrapper the suite uses.
"""

from __future__ import annotations

from agentcage.cli import main

if __name__ == "__main__":
    main()
