#!/usr/bin/env python3
"""Generate the Homebrew formula and the AUR PKGBUILD for a release.

Both files pin a version *and* a checksum for every platform, which
makes both of them wrong the moment a release ships and right again only
when someone regenerates them. Hand-copying four checksums per release
is how a tap ends up installing the previous version, so neither file is
committed in a filled-in state — this produces them from the checksums
the release actually published.

Two sources, because there are two moments you need this:

  --dist DIR        the assets a release build just produced, before
                    anything is published;
  --from-release    the assets already attached to the GitHub release,
                    which is what a maintainer updating a tap has.

Writes `agentcage.rb` and `PKGBUILD` into --out (default: the current
directory). Neither is committed to this repository; see
packaging/README.md for where they go.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

REPO = "agentcage/agentcage"

#: The four released targets, and how each names itself downstream.
#:
#: `brew` picks by `OS.mac`/`Hardware::CPU`, `makepkg` by `$CARCH`. Both
#: spellings are here so neither file has to derive it.
TARGETS = {
    "x86_64-unknown-linux-musl": {"os": "linux", "brew": "intel", "arch": "x86_64"},
    "aarch64-unknown-linux-musl": {"os": "linux", "brew": "arm", "arch": "aarch64"},
    "x86_64-apple-darwin": {"os": "macos", "brew": "intel", "arch": "x86_64"},
    "aarch64-apple-darwin": {"os": "macos", "brew": "arm", "arch": "aarch64"},
}


def asset(version: str, target: str) -> str:
    return f"agentcage-{version}-{target}.tar.gz"


def checksums_from_dist(version: str, dist: Path) -> dict[str, str]:
    sums = {}
    for target in TARGETS:
        path = dist / f"{asset(version, target)}.sha256"
        if not path.is_file():
            raise SystemExit(f"missing {path} — was {target} built?")
        sums[target] = path.read_text().split()[0]
    return sums


def checksums_from_release(version: str) -> dict[str, str]:
    """Read each `.sha256` straight off the published release."""
    sums = {}
    for target in TARGETS:
        url = (
            f"https://github.com/{REPO}/releases/download/"
            f"v{version}/{asset(version, target)}.sha256"
        )
        try:
            with urllib.request.urlopen(url) as response:  # noqa: S310
                sums[target] = response.read().decode().split()[0]
        except Exception as error:  # noqa: BLE001
            raise SystemExit(f"could not read {url}: {error}") from error
    return sums


def formula(version: str, sums: dict[str, str]) -> str:
    """The Homebrew formula.

    `depends_on "podman"` is deliberate and deliberately not `:optional`:
    agentcage without a container runtime starts nothing, and a formula
    that installs a binary which cannot work is worse than one that
    pulls a dependency the user may already have.
    """
    def block(target: str) -> str:
        return (
            f'      url "https://github.com/{REPO}/releases/download/'
            f'v{version}/{asset(version, target)}"\n'
            f'      sha256 "{sums[target]}"'
        )

    return f"""# Generated by scripts/gen-packaging.py — do not hand-edit.
#
# Regenerate on every release:
#   python3 scripts/gen-packaging.py --version <version> --from-release
class Agentcage < Formula
  desc "Defense-in-depth proxy sandbox for AI agents"
  homepage "https://github.com/{REPO}"
  version "{version}"
  license "MIT"

  depends_on "podman"

  on_macos do
    on_arm do
{block("aarch64-apple-darwin")}
    end
    on_intel do
{block("x86_64-apple-darwin")}
    end
  end

  on_linux do
    on_arm do
{block("aarch64-unknown-linux-musl")}
    end
    on_intel do
{block("x86_64-unknown-linux-musl")}
    end
  end

  def install
    bin.install "agentcage"
  end

  test do
    assert_match "agentcage, version #{{version}}", shell_output("#{{bin}}/agentcage --version")
  end
end
"""


def pkgbuild(version: str, sums: dict[str, str]) -> str:
    """The AUR `PKGBUILD`, as `agentcage-bin`.

    `-bin` because it installs a released binary rather than building
    from source, which is the AUR's naming rule and not a preference.
    """
    return f"""# Generated by scripts/gen-packaging.py — do not hand-edit.
#
# Regenerate on every release, then `makepkg --printsrcinfo > .SRCINFO`:
#   python3 scripts/gen-packaging.py --version <version> --from-release
#
# Maintainer: Luca Martinetti <luca@luca.io>
pkgname=agentcage-bin
pkgver={version}
pkgrel=1
pkgdesc="Defense-in-depth proxy sandbox for AI agents"
arch=('x86_64' 'aarch64')
url="https://github.com/{REPO}"
license=('MIT')
depends=('podman')
optdepends=('lima: microVM (isolation: vm) backend')
provides=('agentcage')
conflicts=('agentcage')

_base="$url/releases/download/v$pkgver"
source_x86_64=("$_base/{asset(version, 'x86_64-unknown-linux-musl')}")
source_aarch64=("$_base/{asset(version, 'aarch64-unknown-linux-musl')}")
sha256sums_x86_64=('{sums["x86_64-unknown-linux-musl"]}')
sha256sums_aarch64=('{sums["aarch64-unknown-linux-musl"]}')

package() {{
  local _target
  case "$CARCH" in
    x86_64)  _target=x86_64-unknown-linux-musl ;;
    aarch64) _target=aarch64-unknown-linux-musl ;;
  esac
  cd "agentcage-$pkgver-$_target"
  install -Dm755 agentcage "$pkgdir/usr/bin/agentcage"
  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
  install -Dm644 README.md "$pkgdir/usr/share/doc/$pkgname/README.md"
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="release version, without the leading v")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--dist", type=Path, help="directory of built release assets")
    source.add_argument("--from-release", action="store_true",
                        help="read checksums off the published GitHub release")
    parser.add_argument("--out", type=Path, default=Path("."), help="where to write (default: .)")
    args = parser.parse_args()

    version = args.version.lstrip("v")
    sums = (
        checksums_from_release(version) if args.from_release
        else checksums_from_dist(version, args.dist)
    )

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "agentcage.rb").write_text(formula(version, sums))
    (args.out / "PKGBUILD").write_text(pkgbuild(version, sums))
    print(f"wrote {args.out / 'agentcage.rb'}")
    print(f"wrote {args.out / 'PKGBUILD'}")
    for target, digest in sorted(sums.items()):
        print(f"  {target:32} {digest[:16]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
